[package]
name = "guano-wasm"
version = "0.0.1"
edition = "2024"
license = "MIT"
authors = ["vogelwarte.ch", "Mario Fischer"]

[dependencies]
guano-rs = { path = "../guano-rs" }
wasm-bindgen = "0.2.105"
web-sys = { version = "0.3.82", features = ["Exception", "console"] }

[profile.release]
lto = true

[lib]
crate-type = ["cdylib"]

[dev-dependencies]
wasm-bindgen-test = "0.3.55"
